name:  App Builder

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    env:
      repository: ${{ github.repository }}
      tag: ${{ github.ref_name }}
      event: ${{ github.event_name }} on ${{ github.ref_name }}
      sha: ${{ github.sha }}
      commit: ${{ github.event.head_commit.message }}
      author: ${{ github.event.pusher.name }}
      authorURL: https://github.com/${{ github.event.pusher.name }}
      url: https://github.com/${{ github.repository }}
      releaseURL: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'

      - name: Build measurement module
        run: |
          go build -a -ldflags "-linkmode external -extldflags '-static' -s -w" -o dist/olt-blueprint-measurement-${{ env.tag }} measurement/cmd/main.go

      - name: Build traffic module
        run: |
          go build -a -ldflags "-linkmode external -extldflags '-static' -s -w" -o dist/olt-blueprint-traffic-${{ env.tag }} traffic/cmd/main.go

      - name: Build auth module
        run: |
          go build -a -ldflags "-linkmode external -extldflags '-static' -s -w" -o dist/olt-blueprint-auth-${{ env.tag }} auth/cmd/main.go

      - name: Build report module
        run: |
          go build -a -ldflags "-linkmode external -extldflags '-static' -s -w" -o dist/olt-blueprint-report-${{ env.tag }} report/cmd/main.go

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ./dist/*
          name: OLT Blueprint
          draft: false
          prerelease: false

      - name: Telegram Alert
        id: telegram
        uses: metalpoch/telegram-alerts-action@v1
        with:
          bot-token-id: ${{ secrets.BOT_TOKEN_ID }}
          chat-id: ${{ secrets.CHAT_ID }}
          disable-web-page-preview: true
          text: "*New Release*\n\n
            *🎟 Event:* `${{ env.event }}`\n\n
            *🔑 SHA:* `${{ env.sha }}`\n\n
            *📝 Commit:* `${{ env.commit }}`\n\n
            *🔗 Links:*\n
            \t\t\t[🗃 Repository](${{ env.url }})\n
            \t\t\t[📦 Releases](${{ env.releaseURL }})\n\n
            *👤 Author:* [${{ env.author }}](${{ env.authorURL }})"